feat: ✨ create and edit student
PedakiHQ/pedaki-community pull request #167
Opened 2024-03-13 13:31 UTC by AvaN0x

Closes #

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

## ✅ Checklist

- [ ] I have followed the steps listed in the [Contributing guide](https://github.com/pedakihq/pedaki/blob/main/CONTRIBUTING.md).
- [ ] I have added or updated the tests related to the changes made.

2024-03-13 16:09 UTC, Vahor requested changes

2024-03-13 16:09 UTC, Vahor commented on app/src/components/students/one/edit-student-form.tsx
> +const EditStudentFormSchema = StudentSchema.pick({
Est-ce que tu peux utiliser omit ici ?

2024-03-13 17:47 UTC, Vahor commented
Aussi j'y penses là, est-ce qu'on peut ajouter une fonction pour supprimer un élève ?

2024-03-14 06:45 UTC, AvaN0x commented
Yes on peut, je regarderai pour ça

2024-03-14 18:45 UTC, Vahor commented
Quand on n'a pas de propriété l'update fail avec
```
@pedaki/community:dev: prisma:query UPDATE students
@pedaki/community:dev:                 SET first_name = 'Child', last_name = 'Chrysteld', other_name = 'ÖrjanFèi', gender = 'F', birth_date = '2017-04-29 02:00:00.000', properties = properties ||
@pedaki/community:dev:                 WHERE id = 207
@pedaki/community:dev: prisma:error
@pedaki/community:dev: Invalid `prisma.$queryRawUnsafe()` invocation:
@pedaki/community:dev: Raw query failed. Code: `42601`. Message: `ERROR: syntax error at or near "WHERE"`

```

2024-03-15 21:14 UTC, merged