feat: ✨ use proper texts with i18n
PedakiHQ/pedaki-community pull request #92
Opened 2023-12-31 11:10 UTC by AvaN0x

Closes #

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

## ✅ Checklist

- [ ] I have followed the steps listed in the [Contributing guide](https://github.com/pedakihq/pedaki/blob/main/CONTRIBUTING.md).
- [ ] I have added or updated the tests related to the changes made.

2023-12-31 11:17 UTC, AvaN0x commented
Suggested edit:
```diff
diff --git a/app/src/app/[locale]/(main)/layout.tsx b/app/src/app/[locale]/(main)/layout.tsx
index 8596f88..21fef82 100644
--- a/app/src/app/[locale]/(main)/layout.tsx
+++ b/app/src/app/[locale]/(main)/layout.tsx
@@ -13,9 +13,7 @@ const TutorialProvider = dynamic(() => import('~/components/tutorial/TutorialPro
 export default function MainLayout({ children, params }: LayoutType) {
   return (
     <>
-      <I18nProviderClient locale={params.locale}>
-        <DemoBanner />
-      </I18nProviderClient>
+      <DemoBanner locale={params.locale} />
 
       <div className="relative h-full peer-data-[visible=true]:mt-12">
         <AuthProvider>
diff --git a/app/src/components/DemoBanner/wrapper.tsx b/app/src/components/DemoBanner/wrapper.tsx
index 53126d4..0d43283 100644
--- a/app/src/components/DemoBanner/wrapper.tsx
+++ b/app/src/components/DemoBanner/wrapper.tsx
@@ -1,15 +1,24 @@
 import { env } from '~/env.ts';
+import { I18nProviderClient } from '~/locales/client';
 import dynamic from 'next/dynamic';
 import React from 'react';
 
 const DemoBannerComponent = dynamic(() => import('./client'), { ssr: true });
 
-const DemoBanner = () => {
+interface DemoBannerProps {
+  locale: string;
+}
+
+const DemoBanner = ({ locale }: DemoBannerProps) => {
   if (!env.NEXT_PUBLIC_IS_DEMO) {
     return null;
   }
 
-  return <DemoBannerComponent />;
+  return (
+    <I18nProviderClient locale={locale}>
+      <DemoBannerComponent />
+    </I18nProviderClient>
+  );
 };
 
 export default DemoBanner;

```

2023-12-31 18:14 UTC, Vahor requested changes

2023-12-31 18:14 UTC, Vahor commented on packages/db/tsup.config.ts
> -  entry: ['src/**/*.(tsx|ts|cjs)'],
Le problème n'est que sur windows, parce que windows est idiot.

On a besoin de ces fichiers dans le build final

2023-12-31 18:20 UTC, Vahor commented on packages/db/tsup.config.ts
> -  entry: ['src/**/*.(tsx|ts|cjs)'],
En solution temporaire tu peux mettre un 
```ts
// TODO: bug on windows with the migrations folder
entry: process.env.NODE_END === "development" ? ['src/*.(tsx|ts|cjs)'] : ['src/**/*.(tsx|ts|cjs)']
```

(ou skip uniquement le dossier migrations)

et je pense que tu peux laisser les autres tsup config à **, ils n'ont pas de soucis eux

2024-01-01 14:45 UTC, AvaN0x commented on packages/db/tsup.config.ts
> -  entry: ['src/**/*.(tsx|ts|cjs)'],
J'ai modifié

2024-01-14 19:44 UTC, Vahor requested changes

2024-01-14 19:44 UTC, Vahor commented on app/src/locales/zod.ts
> +  locale,
Ici ça serait mieux de l'appeler `key` ?

2024-01-14 19:54 UTC, Vahor commented on app/src/components/I18nProviderClient.tsx
> +      <I18nProviderClientContent>{children}</I18nProviderClientContent>
ça devrait aussi marcher avec
```
<OriginalI18nProviderClient locale={locale}>
{children}
  <I18nProviderClientContent/>
</OriginalI18nProviderClient>
  ```
on peut surement retirer le children

2024-01-15 17:09 UTC, AvaN0x commented on app/src/locales/zod.ts
> +  locale,
Je le change

2024-01-15 17:25 UTC, AvaN0x commented on app/src/components/I18nProviderClient.tsx
> +      <I18nProviderClientContent>{children}</I18nProviderClientContent>
Je confirme, je viens de le changer

2024-01-19 13:51 UTC, merged